parameters:
    mailer.model.class:         AppBundle\Model\Mailer
#    export.helper.class:        AppBundle\Helpers\ExportHelper
#    domain.helper.class:        AppBundle\Helpers\DomainHelper

services:
    # ==== Invoice helper
#    invoice.helper:
#        class: '%invoice.helper.class%'
#        lazy:  true
#        arguments: 
#            - '@doctrine.orm.entity_manager'
#            - '@templating'
#            - '@knp_snappy.pdf'
#            - '%invoice_folder%'
#            - '@aws.s3.model'
#            - '@translator.default'
