parameters:
    check_parentheses.helper.class: AppBundle\Helpers\CheckParenthesesHelper

services:
    #  ChekParenthesis helper
    check_parentheses.helper:
        class: '%check_parentheses.helper.class%'
        lazy:  true
        arguments: 

