<?php

namespace Proxies\__CG__\Diagomail\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CreditPackages extends \Diagomail\AppBundle\Entity\CreditPackages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'id', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'quantity', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'sends', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'description', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'creditBalanceTransaction', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'userProperties', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'public'];
        }

        return ['__isInitialized__', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'id', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'quantity', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'sends', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'description', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'creditBalanceTransaction', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'userProperties', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\CreditPackages' . "\0" . 'public'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CreditPackages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSends($sends)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSends', [$sends]);

        return parent::setSends($sends);
    }

    /**
     * {@inheritDoc}
     */
    public function getSends()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSends', []);

        return parent::getSends();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserProperty(\Diagomail\UsersBundle\Entity\UserProperties $userProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserProperty', [$userProperty]);

        return parent::addUserProperty($userProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserProperty(\Diagomail\UsersBundle\Entity\UserProperties $userProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserProperty', [$userProperty]);

        return parent::removeUserProperty($userProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserProperties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserProperties', []);

        return parent::getUserProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreditBalanceTransaction(\Diagomail\AppBundle\Entity\CreditBalanceTransaction $creditBalanceTransaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreditBalanceTransaction', [$creditBalanceTransaction]);

        return parent::addCreditBalanceTransaction($creditBalanceTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreditBalanceTransaction(\Diagomail\AppBundle\Entity\CreditBalanceTransaction $creditBalanceTransaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreditBalanceTransaction', [$creditBalanceTransaction]);

        return parent::removeCreditBalanceTransaction($creditBalanceTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditBalanceTransaction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditBalanceTransaction', []);

        return parent::getCreditBalanceTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublic($public)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublic', [$public]);

        return parent::setPublic($public);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublic', []);

        return parent::getPublic();
    }

}
