<?php

namespace Proxies\__CG__\Diagomail\UsersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserSettings extends \Diagomail\UsersBundle\Entity\UserSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'id', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'trackOpen', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'trackClick', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'unsuscribeHeader', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'plainText', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'bounceNotificationsEmail', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'unsuscribeFooter', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'footerText', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'id', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'trackOpen', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'trackClick', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'unsuscribeHeader', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'plainText', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'bounceNotificationsEmail', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'unsuscribeFooter', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'footerText', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserSettings' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackOpen($trackOpen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackOpen', [$trackOpen]);

        return parent::setTrackOpen($trackOpen);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackOpen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackOpen', []);

        return parent::getTrackOpen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackClick($trackClick)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackClick', [$trackClick]);

        return parent::setTrackClick($trackClick);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackClick()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackClick', []);

        return parent::getTrackClick();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainText($plainText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainText', [$plainText]);

        return parent::setPlainText($plainText);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainText', []);

        return parent::getPlainText();
    }

    /**
     * {@inheritDoc}
     */
    public function setFooterText($footerText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFooterText', [$footerText]);

        return parent::setFooterText($footerText);
    }

    /**
     * {@inheritDoc}
     */
    public function getFooterText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFooterText', []);

        return parent::getFooterText();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Diagomail\UsersBundle\Entity\Users $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnsuscribeHeader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnsuscribeHeader', []);

        return parent::getUnsuscribeHeader();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnsuscribeHeader($unsuscribeHeader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnsuscribeHeader', [$unsuscribeHeader]);

        return parent::setUnsuscribeHeader($unsuscribeHeader);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnsuscribeFooter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnsuscribeFooter', []);

        return parent::getUnsuscribeFooter();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnsuscribeFooter($unsuscribeFooter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnsuscribeFooter', [$unsuscribeFooter]);

        return parent::setUnsuscribeFooter($unsuscribeFooter);
    }

    /**
     * {@inheritDoc}
     */
    public function setBounceNotificationsEmail($bounceNotificationsEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBounceNotificationsEmail', [$bounceNotificationsEmail]);

        return parent::setBounceNotificationsEmail($bounceNotificationsEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getBounceNotificationsEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBounceNotificationsEmail', []);

        return parent::getBounceNotificationsEmail();
    }

}
