<?php

namespace Proxies\__CG__\Diagomail\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WebhookEvent extends \Diagomail\AppBundle\Entity\WebhookEvent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'id', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'creationDate', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'modificationDate', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'enable', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'webhooks', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'event', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'webhookEventLog'];
        }

        return ['__isInitialized__', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'id', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'creationDate', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'modificationDate', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'enable', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'webhooks', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'event', '' . "\0" . 'Diagomail\\AppBundle\\Entity\\WebhookEvent' . "\0" . 'webhookEventLog'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WebhookEvent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDate($creationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDate', [$creationDate]);

        return parent::setCreationDate($creationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDate', []);

        return parent::getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setModificationDate($modificationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModificationDate', [$modificationDate]);

        return parent::setModificationDate($modificationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getModificationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModificationDate', []);

        return parent::getModificationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnable($enable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnable', [$enable]);

        return parent::setEnable($enable);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnable', []);

        return parent::getEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebhooks(\Diagomail\AppBundle\Entity\Webhooks $webhooks = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebhooks', [$webhooks]);

        return parent::setWebhooks($webhooks);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebhooks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebhooks', []);

        return parent::getWebhooks();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvent(\Diagomail\AppBundle\Entity\Events $event = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvent', [$event]);

        return parent::setEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvent', []);

        return parent::getEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function addWebhookEventLog(\Diagomail\AppBundle\Entity\WebhookEventLog $webhookEventLog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWebhookEventLog', [$webhookEventLog]);

        return parent::addWebhookEventLog($webhookEventLog);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWebhookEventLog(\Diagomail\AppBundle\Entity\WebhookEventLog $webhookEventLog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWebhookEventLog', [$webhookEventLog]);

        return parent::removeWebhookEventLog($webhookEventLog);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebhookEventLog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebhookEventLog', []);

        return parent::getWebhookEventLog();
    }

}
