<?php

namespace Proxies\__CG__\Diagomail\UsersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserProperties extends \Diagomail\UsersBundle\Entity\UserProperties implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'id', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'creationDate', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'quotaHourly', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'advertiserId', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'advertiserCpm', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'creditPackage', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'reputationLevel', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'accountType', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'timezone', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'creditBalanceTransaction', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'languages', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'emailBillingNotifications', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'manualQuota', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'company', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'id', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'creationDate', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'quotaHourly', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'advertiserId', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'advertiserCpm', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'creditPackage', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'reputationLevel', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'accountType', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'timezone', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'creditBalanceTransaction', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'languages', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'emailBillingNotifications', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'manualQuota', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'company', '' . "\0" . 'Diagomail\\UsersBundle\\Entity\\UserProperties' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserProperties $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDate($creationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDate', [$creationDate]);

        return parent::setCreationDate($creationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDate', []);

        return parent::getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuotaHourly($quotaHourly)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuotaHourly', [$quotaHourly]);

        return parent::setQuotaHourly($quotaHourly);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuotaHourly()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuotaHourly', []);

        return parent::getQuotaHourly();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountType(\Diagomail\UsersBundle\Entity\AccountType $accountType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountType', [$accountType]);

        return parent::setAccountType($accountType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountType', []);

        return parent::getAccountType();
    }

    /**
     * {@inheritDoc}
     */
    public function setReputationLevel(\Diagomail\UsersBundle\Entity\UserReputationLevel $reputationLevel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReputationLevel', [$reputationLevel]);

        return parent::setReputationLevel($reputationLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getReputationLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReputationLevel', []);

        return parent::getReputationLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimezone(\Diagomail\UsersBundle\Entity\Timezone $timezone = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimezone', [$timezone]);

        return parent::setTimezone($timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimezone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimezone', []);

        return parent::getTimezone();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguages(\Diagomail\UsersBundle\Entity\Languages $languages = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguages', [$languages]);

        return parent::setLanguages($languages);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguages', []);

        return parent::getLanguages();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Diagomail\UsersBundle\Entity\Users $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(\Diagomail\UsersBundle\Entity\Company $company = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditPackage(\Diagomail\AppBundle\Entity\CreditPackages $creditPackage = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditPackage', [$creditPackage]);

        return parent::setCreditPackage($creditPackage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditPackage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditPackage', []);

        return parent::getCreditPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailBillingNotifications($emailBillingNotifications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailBillingNotifications', [$emailBillingNotifications]);

        return parent::setEmailBillingNotifications($emailBillingNotifications);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailBillingNotifications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailBillingNotifications', []);

        return parent::getEmailBillingNotifications();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreditBalanceTransaction(\Diagomail\AppBundle\Entity\CreditBalanceTransaction $creditBalanceTransaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreditBalanceTransaction', [$creditBalanceTransaction]);

        return parent::addCreditBalanceTransaction($creditBalanceTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreditBalanceTransaction(\Diagomail\AppBundle\Entity\CreditBalanceTransaction $creditBalanceTransaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreditBalanceTransaction', [$creditBalanceTransaction]);

        return parent::removeCreditBalanceTransaction($creditBalanceTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditBalanceTransaction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditBalanceTransaction', []);

        return parent::getCreditBalanceTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdvertiserId($advertiserId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdvertiserId', [$advertiserId]);

        return parent::setAdvertiserId($advertiserId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdvertiserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdvertiserId', []);

        return parent::getAdvertiserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdvertiserCpm($advertiserCpm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdvertiserCpm', [$advertiserCpm]);

        return parent::setAdvertiserCpm($advertiserCpm);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdvertiserCpm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdvertiserCpm', []);

        return parent::getAdvertiserCpm();
    }

    /**
     * {@inheritDoc}
     */
    public function setManualQuota($manualQuota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManualQuota', [$manualQuota]);

        return parent::setManualQuota($manualQuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getManualQuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManualQuota', []);

        return parent::getManualQuota();
    }

}
